import { ArrowUpRight, BarChart3 } from "lucide-react";
import { commonProblems, profileProblems, versionSegments } from "@/data/mockInsights";

export default function ProblemsPage() {
  const maxCases = Math.max(...commonProblems.map((item) => item.cases));
  return <main className="p-4 sm:p-7 lg:p-9"><div className="mx-auto max-w-7xl"><div className="mb-7"><p className="text-sm font-bold text-primary">PADRÕES</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Problemas comuns</h1><p className="mt-2 text-slate-500">Maior incidência observada nos dados demonstrativos.</p></div><div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-6 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-primary"><BarChart3 className="size-5" /></span><div><h2 className="font-bold text-slate-950">Ocorrências mais frequentes</h2><p className="text-sm text-slate-500">Últimos 7 dias</p></div></div><div className="space-y-6">{commonProblems.map((problem) => <div key={problem.name}><div className="mb-2 flex items-end justify-between gap-4"><div><p className="font-semibold text-slate-900">{problem.name}</p><p className="text-sm text-slate-500">{problem.cases} casos</p></div><span className="flex items-center gap-1 text-sm font-bold text-emerald-700"><ArrowUpRight className="size-4" />{problem.change}</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full" style={{ width: `${(problem.cases / maxCases) * 100}%`, backgroundColor: problem.color }} /></div></div>)}</div></section>
    <section className="rounded-2xl border border-slate-200 bg-slate-950 p-6 text-white shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-blue-300">Perfil dos usuários afetados</p><h2 className="mt-2 text-xl font-bold">Versão do sistema</h2><div className="mt-8 grid grid-cols-[150px_1fr] items-center gap-6"><div className="relative mx-auto grid size-36 place-items-center rounded-full" style={{ background: "conic-gradient(#4c7dff 0 42%, #14b8a6 42% 73%, #7c3aed 73% 91%, #64748b 91%)" }}><div className="grid size-24 place-items-center rounded-full bg-slate-950 text-center"><div><p className="text-2xl font-bold">3.2</p><p className="text-xs text-slate-400">mais afetada</p></div></div></div><div className="space-y-3">{versionSegments.map((segment, index) => <div key={segment.label} className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-slate-300"><span className="size-2.5 rounded-full" style={{ backgroundColor: ["#4c7dff", "#14b8a6", "#7c3aed", "#64748b"][index] }} />{segment.label}</span><span className="font-bold">{segment.value}%</span></div>)}</div></div><p className="mt-7 border-t border-white/10 pt-4 text-xs leading-5 text-slate-400">Dados demonstrativos. Os percentuais representam incidência observada, não previsão.</p></section>
  </div><section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-950">Problemas por perfil</h2><p className="mt-1 text-sm text-slate-500">Categorias com maior incidência observada.</p><div className="mt-6 grid gap-4 md:grid-cols-3">{profileProblems.map((item) => <article key={item.profile} className="rounded-2xl border border-slate-200 p-5"><h3 className="font-bold text-slate-900">{item.profile}</h3><div className="mt-5 space-y-4">{[[item.primary,item.primaryValue],[item.secondary,item.secondaryValue]].map(([label,value], index) => <div key={label}><div className="mb-2 flex justify-between text-sm"><span className="text-slate-600">{label}</span><span className="font-bold">{value}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${index ? "bg-teal-500" : "bg-primary"}`} style={{ width: `${value}%` }} /></div></div>)}</div></article>)}</div></section></div></main>;
}
