import { CheckCircle2, TrendingUp } from "lucide-react";
import { InsightCard } from "@/components/InsightCard";
import { insights } from "@/data/mockInsights";

export default function InsightsPage() {
  return <main className="p-4 sm:p-7 lg:p-9"><div className="mx-auto max-w-7xl"><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-primary">LEITURAS DA OPERAÇÃO</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Insights</h1><p className="mt-2 text-slate-500">Sinais que ajudam o suporte a decidir onde agir primeiro.</p></div><span className="w-fit rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-500">Dados demonstrativos</span></div><section className="grid gap-4 md:grid-cols-2">{insights.map((insight) => <InsightCard key={insight.title} insight={insight} />)}</section><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_.7fr]">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><TrendingUp className="size-5" /></span><div><h2 className="font-bold text-slate-950">Oportunidade mais clara</h2><p className="text-sm text-slate-500">Reduzir perguntas repetidas na abertura</p></div></div><div className="mt-7 grid gap-4 sm:grid-cols-3">{[["80%","do suporte sente falta de mensagens de erro"],["80%","sente falta de prints da tela"],["100%","relata impacto em tempo e retrabalho"]].map(([value,label]) => <div key={label} className="rounded-2xl bg-slate-50 p-4"><p className="text-2xl font-bold text-slate-950">{value}</p><p className="mt-2 text-sm leading-5 text-slate-500">{label}</p></div>)}</div></section>
    <section className="rounded-2xl bg-primary p-6 text-white shadow-[0_18px_50px_rgba(13,72,255,.22)]"><p className="text-sm font-bold text-blue-100">PRÓXIMO PASSO SUGERIDO</p><h2 className="mt-3 text-xl font-bold">Padronizar evidências por cenário</h2><ul className="mt-6 space-y-4">{["Código ou texto do erro", "Ação realizada antes da falha", "Alcance entre usuários", "Frequência e horário"].map((item) => <li key={item} className="flex gap-3 text-sm text-blue-50"><CheckCircle2 className="size-5 shrink-0" />{item}</li>)}</ul></section>
  </div></div></main>;
}
